### ISSUE TITLE
raxml or raxml-ng？

### ISSUE THREAD

**Issue by zhangwenda0518** [bpucker/bHLH_annotator#1]
Hello, I want to make sure whether we use raxml or raxml-ng 。
I saw in the **readme** file that raxml-ng was installed during manual installation, but in the **environment.yml** file, it installed raxml.
I checked the script bHLH_annotator.py and searched raxml. 
The 168-line command in the script is 
`p = subprocess.popen (args = "".join ([Raxml, "-all-threads"+str (CPUR)+"-model LG+G8+f-MSA"). X_cln_aln_file, "--prefix", prefix ] ), shell=True )`

This should be the parameters and running mode of raxml-ng.

However, I reported an error, and there was no raxml command after install raxml-ng，Should I rename raxml-ng raxml?

thanks！

**Comment by c-thoben** [comment]
Hello, 

you are right, the tool is intended to be used with raxml-ng. I falsely included raxml instead of raxml-ng in the environment and the command for raxml in the bHLH_annotator pipeline was wrong. I changed both to raxml-ng so if you set up a new environment the bHLH_annotator should be able to run with raxml-ng. The argument "raxml" for the --mode_tree is still  the same.

Thanks for reporting this error and sorry for the confusion. I hope everything will now run fine.

Have a nice day!

**Comment by zhangwenda0518** [comment]
Have a nice day!
